pipeline {
    agent any

    // This file is required to sign the binaries for Windows and MacOs, see https://wiki.eclipse.org/IT_Infrastructure_Doc#Sign_my_Jar.2Fplugins.2FWindows_exe.2FmacOS_App_files.3F

    stages {
        stage('Download') {
            steps {
                script {
                    sh 'curl -L https://github.com/eclipse-esmf/esmf-aspect-model-editor-backend/releases/download/v5.1.1/ame-backend-5.1.1-win.exe -o ame-backend-5.1.1-win.exe'
                }
            }
        }

        stage('Sign Windows') {
            steps {
                script {
                    sh 'curl -o signed.exe -F file=@ame-backend-5.1.1-win.exe https://cbi.eclipse.org/authenticode/sign'
                }
            }
        }

        stage('Install GH CLI') {
            steps {
                script {
                    sh 'if ! command -v gh &> /dev/null; then echo "gh could not be found, installing..."; sudo apt update && sudo apt install gh -y; else echo "gh is already installed"; fi'
                }
            }
        }

        stage('Verify GH CLI Installation') {
            steps {
                script {
                    sh 'gh --version'
                }
            }
        }

        stage('Upload Signed File') {
            steps {
                script {
                    sh "gh release upload v5.2.1 signed.exe --clobber"
                }
            }
        }
    }
}
