pipeline {
    agent any

    // This file is required to sign the binaries for Windows and MacOs, see https://wiki.eclipse.org/IT_Infrastructure_Doc#Sign_my_Jar.2Fplugins.2FWindows_exe.2FmacOS_App_files.3F

    environment {
        GITHUB_TOKEN = credentials('github-bot')
    }

    stages {
        stage('Download') {
            steps {
                script {
                    sh 'curl -L https://github.com/eclipse-esmf/esmf-aspect-model-editor-backend/releases/download/v5.1.1/ame-backend-5.1.1-win.exe -o ame-backend-5.1.1-win.exe'
                }
            }
        }

        stage('Sign Windows') {
            steps {
                script {
                    sh 'curl -o signed.exe -F file=@ame-backend-5.1.1-win.exe https://cbi.eclipse.org/authenticode/sign'
                }
            }
        }

        stage('Upload File to GitHub Release') {
            steps {
                script {
                    def repo = "eclipse-esmf/esmf-aspect-model-editor-backend"
                    def releaseId = "v5.2.1"
                    def fileName = "signed.exe"
                    def uploadUrl = "https://uploads.github.com/repos/${repo}/releases/${releaseId}/assets?name=${fileName}" as Object

                    sh script: """
                        curl -L \
                             -X POST \
                             -H "Accept: application/vnd.github+json" \\
                             -H "Authorization: Bearer \$GITHUB_TOKEN" \
                             -H "Content-Type: application/octet-stream" \
                             --data-binary @${fileName} \
                             "${uploadUrl}"
                    """, env: ['GITHUB_TOKEN': env.GITHUB_TOKEN]
                }
            }
        }
    }
}
