name: Check New Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

permissions: { }

jobs:
  build:
    name: Check if passes all requirements
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-15-intel, windows-latest, ubuntu-latest ]

    steps:
      - name: Checkout project
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Configure Pagefile
        if: matrix.os == 'windows-latest'
        # Fix for "LINK : fatal error LNK1171: unable to load mspdbcore.dll (error code: 1455)":
        # This seems to be caused by running out of memory; increasing page file
        # size suggested here:
        # https://github.com/actions/virtual-environments/issues/3420#issuecomment-861342418
        uses: al-cheb/configure-pagefile-action@9b6da52fb72a3c6147c1aad2df22d8d905681adc # v1.5
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"

      - name: Setup JDK
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          java-version: '25.0.3'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure Pagefile (Windows)
        if: matrix.os == 'windows-latest'
        # Fix for "LINK : fatal error LNK1171: unable to load mspdbcore.dll (error code: 1455)":
        # This seems to be caused by running out of memory; increasing page file
        # size suggested here:
        # https://github.com/actions/virtual-environments/issues/3420#issuecomment-861342418
        uses: al-cheb/configure-pagefile-action@86589fd789a4de3e62ba628dda2cb10027b66d67 # v1.3
        with:
          minimum-size: 32GB
          maximum-size: 32GB
          disk-root: "C:"

      - name: Set Swap Space (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: pierotofy/set-swap-space@49819abfb41bd9b44fb781159c033dba90353a7c # master
        with:
          swap-size-gb: 12

      - name: Build and run tests
        run: |
          java --version
          export MAVEN_OPTS="-Xmx4096m"
          export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
          # Build aspect model editor executable jar
          unset JAVA_TOOL_OPTIONS
          mvn -B clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=60
        shell: bash

      - name: Build warp packer (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          bundle="aspect-model-editor-bundle-DEV-SNAPSHOT-$(date +%s)"
          mkdir ${bundle}
          curl -Lo jre.tar.gz https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.3%2B9/OpenJDK25U-jre_x64_linux_hotspot_25.0.3_9.tar.gz
          tar -xvf jre.tar.gz -C $bundle
          cp aspect-model-editor-runtime/target/aspect-model-editor-runtime-DEV-SNAPSHOT.jar ./${bundle}/
          
          cat <<EOF > ./${bundle}/run.sh
          #!/usr/bin/env bash

          HERE=\${BASH_SOURCE%/*}

          "\$HERE/jdk-25.0.3+9-jre/bin/java" -jar "\$HERE/aspect-model-editor-runtime-DEV-SNAPSHOT.jar" "\$@"
          EOF
          chmod +x ./${bundle}/run.sh

          curl -Lo warp-packer https://github.com/dgiagio/warp/releases/download/v0.3.0/linux-x64.warp-packer
          chmod +x warp-packer
          
          ./warp-packer --arch linux-x64 --input_dir ${bundle} --exec run.sh --output ame-backend-DEV-SNAPSHOT-linux
          chmod +x ame-backend-DEV-SNAPSHOT-linux
          
          cp ame-backend-DEV-SNAPSHOT-linux aspect-model-editor-runtime/target/
        shell: bash

      - name: Build warp packer (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          $bundle = "aspect-model-editor-bundle-DEV-SNAPSHOT-$([int][double]::Parse((Get-Date -UFormat %s)))"
          mkdir $bundle
          curl -Lo jre.zip https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.3%2B9/OpenJDK25U-jre_x64_windows_hotspot_25.0.3_9.zip
          tar -xf jre.zip -C .\$bundle
          Remove-Item jre.zip

          Move-Item aspect-model-editor-runtime/target/aspect-model-editor-runtime-DEV-SNAPSHOT.jar .\$bundle\
          
          Set-Content -Path .\$bundle\run.bat -Value "@echo off`r`n%~dp0jdk-25.0.3+9-jre\bin\java -jar %~dp0aspect-model-editor-runtime-DEV-SNAPSHOT.jar %*" -Encoding ascii

          curl -Lo warp-packer.exe https://github.com/dgiagio/warp/releases/download/v0.3.0/windows-x64.warp-packer.exe
          .\warp-packer.exe --arch windows-x64 --input_dir $bundle --exec run.bat --output ame-backend-DEV-SNAPSHOT-win.exe

          Remove-Item -Recurse -Force $bundle
          Remove-Item warp-packer.exe

          Move-Item ame-backend-DEV-SNAPSHOT-win.exe aspect-model-editor-runtime/target/
        shell: pwsh

      - name: Build warp packer (Mac)
        if: matrix.os == 'macos-15-intel'
        run: |
          bundle="aspect-model-editor-bundle-DEV-SNAPSHOT-$(date +%s)"
          mkdir ${bundle}
          curl -Lo jre.tar.gz https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.3%2B9/OpenJDK25U-jre_x64_mac_hotspot_25.0.3_9.tar.gz
          tar -xvf jre.tar.gz
          cp -r ./jdk-25.0.3+9-jre ./${bundle}/jre
          cp aspect-model-editor-runtime/target/aspect-model-editor-runtime-DEV-SNAPSHOT.jar ./${bundle}/

          cat <<EOF > ./${bundle}/run.sh
          #!/usr/bin/env bash

          HERE=\${BASH_SOURCE%/*}

          "\$HERE/jre/Contents/Home/bin/java" -jar "\$HERE/aspect-model-editor-runtime-DEV-SNAPSHOT.jar" "\$@"
          EOF
          chmod +x ./${bundle}/run.sh

          curl -Lo warp-packer https://github.com/dgiagio/warp/releases/download/v0.3.0/macos-x64.warp-packer
          chmod +x warp-packer
          
          ./warp-packer --arch macos-x64 --input_dir ${bundle} --exec run.sh --output ame-backend-DEV-SNAPSHOT-mac
          chmod +x ame-backend-DEV-SNAPSHOT-mac

          cp ame-backend-DEV-SNAPSHOT-mac aspect-model-editor-runtime/target/
        shell: bash

      - name: Performing integration test for Mac
        if: matrix.os == 'macos-15-intel'
        run: mvn install -DskipTests -P dependencies-for-integration-tests,start-mac-image-for-integration-tests,run-bruno-integration-tests -Dos.platform=mac
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Performing integration test for Linux
        if: matrix.os == 'ubuntu-latest'
        run: mvn install -DskipTests -P dependencies-for-integration-tests,start-linux-image-for-integration-tests,run-bruno-integration-tests -Dos.platform=linux
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Performing integration test for Windows
        if: matrix.os == 'windows-latest'
        run: mvn install -DskipTests -P dependencies-for-integration-tests,start-windows-image-for-integration-tests,run-bruno-integration-tests -D os.platform=win
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: ame-backend-win
          path: aspect-model-editor-runtime/target/ame-backend-DEV-SNAPSHOT-win.exe

      - name: Upload binary (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: ame-backend-linux
          path: aspect-model-editor-runtime/target/ame-backend-DEV-SNAPSHOT-linux

      - name: Upload binary (Mac)
        if: matrix.os == 'macos-15-intel'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: ame-backend-mac
          path: aspect-model-editor-runtime/target/ame-backend-DEV-SNAPSHOT-mac
          compression-level: 0