name: "Sign Executable"

on:
  push:
  pull_request:
    branches: [ '**' ]
jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job, for singing executable
        run: |
          DATA='{"repository": {"url": "https://github.com/eclipse-cbi/org.eclipse.cbi", "html_url": "https://github.com/eclipse-cbi/org.eclipse.cbi", "owner": { "name": "eclipse-cbi"}}, "pusher": { "name": "foobar", "email": "foo@bar.com"}}'
          SHA1="$(echo -n "${DATA}" | openssl dgst -sha1 -hmac "${WEBHOOK_SECRET}" | sed 's/SHA1(stdin)= //')"
        
          curl -X POST https://ci.eclipse.org/esmf/job/Sign-Native-Image/github-webhook/ -H "Content-Type: application/json" \
          -H "X-GitHub-Event: push" -H "X-Hub-Signature: sha1=${SHA1}" -d "${DATA}" -H 'Jenkins-Crumb: cf0a7a10c4de6bcf1704c8db04fad94d87331830e6d7e05909b7778570573c0c'

