name: "Sign Executable"

on:
  push:
  pull_request:
    branches: [ '**' ]
jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job, for singing executable
        run: |
          curl -X POST https://ci.eclipse.org/esmf/job/Sign-Native-Image/github-webhook/ \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"event_type": "trigger_jenkins"}'
